import { Head, router } from '@inertiajs/react';
import {
    Settings,
    Bell,
    Shield,
    RotateCcw,
    Info,
    Server,
    Database,
    HardDrive,
    Save,
    RefreshCw,
    Calendar,
    AlertCircle,
    CheckCircle2
} from 'lucide-react';
import { useState, useRef } from 'react';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Checkbox } from '@/components/ui/checkbox';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import {
    Select,
    SelectContent,
    SelectItem,
    SelectTrigger,
    SelectValue,
} from '@/components/ui/select';
import { Switch } from '@/components/ui/switch';
import AppLayout from '@/layouts/app-layout';

const NavItem = ({ id, label, icon: Icon, activeTab, onSelect }: { id: string; label: string; icon: any; activeTab: string; onSelect: (id: string) => void }) => (
    <button
        onClick={() => onSelect(id)}
        className={`w-full flex items-center gap-3 px-4 py-2 text-sm font-medium rounded-md transition-colors ${
            activeTab === id
                ? 'bg-slate-100 text-[#1c2434] dark:bg-slate-800 dark:text-white'
                : 'text-slate-600 hover:bg-slate-50 dark:text-slate-400 dark:hover:bg-slate-800/50'
        }`}
    >
        <Icon className="h-4 w-4" />
        {label}
    </button>
);

export default function SettingsPage({ initialDeadline }: { initialDeadline?: string }) {
    const breadcrumbs = [
        {
            title: 'Settings',
            href: '/settings',
        },
    ];

    const [activeTab, setActiveTab] = useState('general');
    const [deadlineDate, setDeadlineDate] = useState(initialDeadline || '');
    const [isSavingDeadline, setIsSavingDeadline] = useState(false);
    const [deadlineMsg, setDeadlineMsg] = useState<string | null>(null);

    const fileInputRef = useRef<HTMLInputElement>(null);
    const [isRestoring, setIsRestoring] = useState(false);
    const [restoreMsg, setRestoreMsg] = useState<{ type: 'success' | 'error'; text: string } | null>(null);

    const handleDownloadBackup = () => {
        window.location.href = '/settings/backup/download';
    };

    const handleTriggerRestore = () => {
        setRestoreMsg(null);
        fileInputRef.current?.click();
    };

    const handleRestoreFileSelected = (e: React.ChangeEvent<HTMLInputElement>) => {
        const file = e.target.files?.[0];
        if (!file) return;

        setRestoreMsg(null);

        if (!confirm(`Are you sure you want to restore database records from file "${file.name}"? Existing data will be updated.`)) {
            if (fileInputRef.current) fileInputRef.current.value = '';
            return;
        }

        setIsRestoring(true);
        const formData = new FormData();
        formData.append('backup_file', file);

        router.post('/settings/backup/restore', formData, {
            onSuccess: (page) => {
                const pageProps = page.props as any;
                const flashErr = pageProps?.flash?.error;
                const validationErr = pageProps?.errors?.backup_file;
                const flashSucc = pageProps?.flash?.success;
                
                if (flashErr || validationErr) {
                    setRestoreMsg({ type: 'error', text: flashErr || validationErr });
                } else if (flashSucc) {
                    setRestoreMsg({ type: 'success', text: flashSucc });
                    setTimeout(() => setRestoreMsg(null), 6000);
                } else {
                    setRestoreMsg({ type: 'error', text: 'Database restore could not be confirmed by the server.' });
                }
            },
            onError: (errs) => {
                setRestoreMsg({ type: 'error', text: errs.backup_file || errs.error || 'Security rejected: Only .json database backup packages generated by Lupon are accepted.' });
            },
            onFinish: () => {
                setIsRestoring(false);
                if (fileInputRef.current) fileInputRef.current.value = '';
            }
        });
    };

    const handleSaveDeadline = (e: React.FormEvent) => {
        e.preventDefault();
        if (!deadlineDate) return;
        setIsSavingDeadline(true);
        setDeadlineMsg(null);

        router.post(
            '/ltia/deadline',
            { deadline_date: deadlineDate },
            {
                preserveScroll: true,
                onSuccess: () => {
                    setIsSavingDeadline(false);
                    setDeadlineMsg('System deadline updated successfully!');
                    setTimeout(() => setDeadlineMsg(null), 4000);
                },
                onError: (errors) => {
                    setIsSavingDeadline(false);
                    setDeadlineMsg(errors.deadline_date || 'Failed to save deadline.');
                },
            }
        );
    };

    const scrollToSection = (id: string) => {
        setActiveTab(id);
        const element = document.getElementById(id);
        if (element) {
            element.scrollIntoView({ behavior: 'smooth' });
        }
    };

    return (
        <AppLayout breadcrumbs={breadcrumbs}>
            <Head title="System Settings" />

            <div className="flex-1 space-y-6 p-4 md:p-8 pt-6 text-slate-900 dark:text-slate-100">
                {/* Header */}
                <div className="flex items-center justify-between">
                    <div>
                        <h2 className="text-2xl font-bold tracking-tight">System Settings</h2>
                        <p className="text-muted-foreground">
                            Configure system preferences and options
                        </p>
                    </div>
                    <div className="flex items-center space-x-2">
                        <Button variant="outline" className="h-9">
                            <RotateCcw className="mr-2 h-4 w-4" />
                            Reset to Default
                        </Button>
                        <Button className="h-9 bg-[#1c2434] hover:bg-[#2c3a4f] text-white">
                            <Save className="mr-2 h-4 w-4" />
                            Save Changes
                        </Button>
                    </div>
                </div>

                <div className="flex flex-col md:flex-row gap-8">
                    {/* Settings Sidebar */}
                    <div className="md:w-64 flex-shrink-0">
                        <div className="sticky top-6 space-y-1">
                            <NavItem id="general" label="General" icon={Settings} activeTab={activeTab} onSelect={scrollToSection} />
                            <NavItem id="deadline" label="Deadline Configuration" icon={Calendar} activeTab={activeTab} onSelect={scrollToSection} />
                            <NavItem id="notifications" label="Notifications" icon={Bell} activeTab={activeTab} onSelect={scrollToSection} />
                            <NavItem id="security" label="Security" icon={Shield} activeTab={activeTab} onSelect={scrollToSection} />
                            <NavItem id="backup" label="Backup & Restore" icon={RotateCcw} activeTab={activeTab} onSelect={scrollToSection} />
                            <NavItem id="system" label="System Info" icon={Info} activeTab={activeTab} onSelect={scrollToSection} />
                        </div>
                    </div>

                    {/* Settings Content */}
                    <div className="flex-1 space-y-8">
                        {/* General Settings */}
                        <section id="general" className="scroll-mt-6">
                            <Card>
                                <CardHeader>
                                    <CardTitle>General Settings</CardTitle>
                                </CardHeader>
                                <CardContent className="space-y-6">
                                    <div className="space-y-2">
                                        <Label htmlFor="barangay-name">Barangay Name</Label>
                                        <Input id="barangay-name" defaultValue="Barangay 183, Villamor Air Base" />
                                    </div>
                                    <div className="space-y-2">
                                        <Label htmlFor="city">City/Municipality</Label>
                                        <Input id="city" defaultValue="Pasay City" />
                                    </div>
                                    <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                                        <div className="space-y-2">
                                            <Label htmlFor="contact">Contact Number</Label>
                                            <Input id="contact" defaultValue="+63 2 0123 4567" />
                                        </div>
                                        <div className="space-y-2">
                                            <Label htmlFor="email">Email Address</Label>
                                            <Input id="email" type="email" defaultValue="brgy183@pasay.gov.ph" />
                                        </div>
                                    </div>
                                    <div className="space-y-2">
                                        <Label>Time Zone</Label>
                                        <Select defaultValue="asia-manila">
                                            <SelectTrigger>
                                                <SelectValue placeholder="Select Time Zone" />
                                            </SelectTrigger>
                                            <SelectContent>
                                                <SelectItem value="asia-manila">Asia/Manila (GMT+8)</SelectItem>
                                                <SelectItem value="utc">UTC</SelectItem>
                                            </SelectContent>
                                        </Select>
                                    </div>
                                    <div className="space-y-2">
                                        <Label>Date Format</Label>
                                        <Select defaultValue="mm-dd-yyyy">
                                            <SelectTrigger>
                                                <SelectValue placeholder="Select Date Format" />
                                            </SelectTrigger>
                                            <SelectContent>
                                                <SelectItem value="mm-dd-yyyy">MM/DD/YYYY</SelectItem>
                                                <SelectItem value="dd-mm-yyyy">DD/MM/YYYY</SelectItem>
                                                <SelectItem value="yyyy-mm-dd">YYYY-MM-DD</SelectItem>
                                            </SelectContent>
                                        </Select>
                                    </div>
                                    <div className="flex items-center justify-between rounded-lg border p-4">
                                        <div className="space-y-0.5">
                                            <Label className="text-base">Enable Case Auto-Numbering</Label>
                                            <p className="text-sm text-muted-foreground">
                                                Automatically generate case numbers
                                            </p>
                                        </div>
                                        <Switch defaultChecked />
                                    </div>
                                </CardContent>
                            </Card>
                        </section>

                        {/* Deadline Configuration */}
                        <section id="deadline" className="scroll-mt-6">
                            <Card>
                                <CardHeader>
                                    <CardTitle className="flex items-center gap-2">
                                        <Calendar className="h-5 w-5 text-[#dd8b11]" />
                                        LTIA & System Deadline Configuration
                                    </CardTitle>
                                    <CardDescription>
                                        Manage the system submission deadline date. Modifying this date automatically adjusts all dependent LTIA application milestone stages.
                                    </CardDescription>
                                </CardHeader>
                                <CardContent className="space-y-6">
                                    <form onSubmit={handleSaveDeadline} className="space-y-4">
                                        {deadlineMsg && (
                                            <div className="p-3 bg-emerald-50 border border-emerald-200 text-emerald-800 dark:bg-emerald-950/40 dark:border-emerald-900 dark:text-emerald-300 rounded-lg text-sm font-medium">
                                                {deadlineMsg}
                                            </div>
                                        )}
                                        <div className="space-y-2">
                                            <Label htmlFor="settings-deadline-input" className="text-sm font-semibold">
                                                Primary System Deadline (Interactive Datepicker)
                                            </Label>
                                            <Input
                                                id="settings-deadline-input"
                                                type="date"
                                                value={deadlineDate}
                                                onChange={(e) => setDeadlineDate(e.target.value)}
                                                className="w-full h-10 font-medium"
                                                required
                                            />
                                            <p className="text-xs text-muted-foreground">
                                                Select a date to set the deadline. The system timeline and milestone progress will automatically update.
                                            </p>
                                        </div>
                                        <Button
                                            type="submit"
                                            disabled={isSavingDeadline}
                                            className="bg-[#1c2434] hover:bg-[#2c3a4f] text-white"
                                        >
                                            <Save className="mr-2 h-4 w-4" />
                                            {isSavingDeadline ? 'Saving...' : 'Save & Synchronize System Deadline'}
                                        </Button>
                                    </form>
                                </CardContent>
                            </Card>
                        </section>

                        {/* Notification Settings */}
                        <section id="notifications" className="scroll-mt-6">
                            <Card>
                                <CardHeader>
                                    <CardTitle>Notification Settings</CardTitle>
                                </CardHeader>
                                <CardContent className="space-y-6">
                                    <div className="flex items-center justify-between rounded-lg border p-4 bg-slate-50 dark:bg-slate-900/50">
                                        <div className="space-y-0.5">
                                            <Label className="text-base">Email Notifications</Label>
                                            <p className="text-sm text-muted-foreground">
                                                Receive notifications via email
                                            </p>
                                        </div>
                                        <Switch defaultChecked />
                                    </div>
                                    <div className="flex items-center justify-between rounded-lg border p-4">
                                        <div className="space-y-0.5">
                                            <Label className="text-base">SMS Notifications</Label>
                                            <p className="text-sm text-muted-foreground">
                                                Receive notifications via SMS
                                            </p>
                                        </div>
                                        <Switch />
                                    </div>
                                    <div className="flex items-center justify-between rounded-lg border p-4 bg-slate-50 dark:bg-slate-900/50">
                                        <div className="space-y-0.5">
                                            <Label className="text-base">New Case Alerts</Label>
                                            <p className="text-sm text-muted-foreground">
                                                Get notified when new cases are filed
                                            </p>
                                        </div>
                                        <Switch defaultChecked />
                                    </div>
                                    <div className="flex items-center justify-between rounded-lg border p-4 bg-slate-50 dark:bg-slate-900/50">
                                        <div className="space-y-0.5">
                                            <Label className="text-base">Hearing Reminders</Label>
                                            <p className="text-sm text-muted-foreground">
                                                Reminders for upcoming hearings
                                            </p>
                                        </div>
                                        <Switch defaultChecked />
                                    </div>
                                    <div className="flex items-center justify-between rounded-lg border p-4 bg-slate-50 dark:bg-slate-900/50">
                                        <div className="space-y-0.5">
                                            <Label className="text-base">Document Generation Alerts</Label>
                                            <p className="text-sm text-muted-foreground">
                                                Notify when documents are generated
                                            </p>
                                        </div>
                                        <Switch defaultChecked />
                                    </div>
                                </CardContent>
                            </Card>
                        </section>

                        {/* Security Settings */}
                        <section id="security" className="scroll-mt-6">
                            <Card>
                                <CardHeader>
                                    <CardTitle>Security Settings</CardTitle>
                                </CardHeader>
                                <CardContent className="space-y-6">
                                    <div className="flex items-center justify-between">
                                        <div className="space-y-0.5">
                                            <Label className="text-base">Two-Factor Authentication</Label>
                                            <p className="text-sm text-muted-foreground">
                                                Add extra security to your account
                                            </p>
                                        </div>
                                        <Switch />
                                    </div>
                                    <div className="space-y-2">
                                        <Label htmlFor="session-timeout">Session Timeout (minutes)</Label>
                                        <Input id="session-timeout" type="number" defaultValue="30" />
                                        <p className="text-xs text-muted-foreground">Auto logout after inactivity</p>
                                    </div>
                                    <div className="space-y-3">
                                        <Label>Password Requirements</Label>
                                        <div className="space-y-2">
                                            <div className="flex items-center space-x-2">
                                                <Checkbox id="min-chars" defaultChecked />
                                                <Label htmlFor="min-chars" className="font-normal text-sm">Minimum 8 characters</Label>
                                            </div>
                                            <div className="flex items-center space-x-2">
                                                <Checkbox id="uppercase" defaultChecked />
                                                <Label htmlFor="uppercase" className="font-normal text-sm">Require uppercase lette</Label>
                                            </div>
                                            <div className="flex items-center space-x-2">
                                                <Checkbox id="numbers" defaultChecked />
                                                <Label htmlFor="numbers" className="font-normal text-sm">Require numbers</Label>
                                            </div>
                                            <div className="flex items-center space-x-2">
                                                <Checkbox id="special" />
                                                <Label htmlFor="special" className="font-normal text-sm">Require special characters</Label>
                                            </div>
                                        </div>
                                    </div>
                                    <Button variant="outline" className="w-full">
                                        Change Password
                                    </Button>
                                </CardContent>
                            </Card>
                        </section>

                        {/* Backup & Restore */}
                        <section id="backup" className="scroll-mt-6">
                            <Card>
                                <CardHeader>
                                    <CardTitle>Backup & Restore</CardTitle>
                                </CardHeader>
                                <CardContent className="space-y-6">
                                    {restoreMsg && (
                                        <div className={`p-3.5 border rounded-lg text-xs flex items-center gap-2 font-medium ${
                                            restoreMsg.type === 'error'
                                                ? 'bg-rose-50 text-rose-800 border-rose-300 dark:bg-rose-950/40 dark:border-rose-900 dark:text-rose-300'
                                                : 'bg-emerald-50 text-emerald-800 border-emerald-300 dark:bg-emerald-950/40 dark:border-emerald-900 dark:text-emerald-300'
                                        }`}>
                                            {restoreMsg.type === 'error' ? (
                                                <AlertCircle className="h-4 w-4 text-rose-600 shrink-0" />
                                            ) : (
                                                <CheckCircle2 className="h-4 w-4 text-emerald-600 shrink-0" />
                                            )}
                                            <span>{restoreMsg.text}</span>
                                        </div>
                                    )}

                                    <div className="flex items-center justify-between rounded-lg border p-4">
                                        <div className="space-y-0.5">
                                            <Label className="text-base">Automatic Backups</Label>
                                            <p className="text-sm text-muted-foreground">
                                                Schedule automatic database backups
                                            </p>
                                        </div>
                                        <Switch defaultChecked />
                                    </div>
                                    <div className="space-y-2">
                                        <Label>Backup Frequency</Label>
                                        <Select defaultValue="daily">
                                            <SelectTrigger>
                                                <SelectValue placeholder="Select Frequency" />
                                            </SelectTrigger>
                                            <SelectContent>
                                                <SelectItem value="daily">Daily</SelectItem>
                                                <SelectItem value="weekly">Weekly</SelectItem>
                                                <SelectItem value="monthly">Monthly</SelectItem>
                                            </SelectContent>
                                        </Select>
                                    </div>
                                    <div className="rounded-lg bg-slate-50 dark:bg-slate-900/50 p-4 flex items-center justify-between text-sm">
                                        <span className="text-muted-foreground">Last Backup</span>
                                        <span className="font-medium">January 10, 2025 - 2:00 AM</span>
                                    </div>
                                    <div className="rounded-lg bg-slate-50 dark:bg-slate-900/50 p-4 flex items-center justify-between text-sm -mt-4">
                                        <span className="text-muted-foreground">Backup Size</span>
                                        <span className="font-medium">215 MB</span>
                                    </div>
                                     <div className="grid grid-cols-2 gap-4">
                                         <Button 
                                             onClick={handleDownloadBackup} 
                                             className="bg-[#1c2434] hover:bg-[#2c3a4f] text-white flex items-center justify-center gap-2"
                                         >
                                             <Database className="h-4 w-4" />
                                             Create Backup Now
                                         </Button>

                                         <Button 
                                             variant="outline" 
                                             onClick={handleTriggerRestore}
                                             disabled={isRestoring}
                                             className="flex items-center justify-center gap-2 border-amber-500/40 text-[#dd8b11] hover:bg-amber-50 dark:hover:bg-amber-950/40"
                                         >
                                             <RotateCcw className={`h-4 w-4 ${isRestoring ? 'animate-spin' : ''}`} />
                                             {isRestoring ? 'Restoring Backup...' : 'Restore from Backup'}
                                         </Button>

                                         <input 
                                             type="file" 
                                             ref={fileInputRef} 
                                             accept=".json,application/json" 
                                             onChange={handleRestoreFileSelected} 
                                             className="hidden" 
                                         />
                                     </div>
                                </CardContent>
                            </Card>
                        </section>

                        {/* System Information */}
                        <section id="system" className="scroll-mt-6">
                            <Card>
                                <CardHeader>
                                    <CardTitle>System Information</CardTitle>
                                </CardHeader>
                                <CardContent className="space-y-6">
                                    <div className="flex items-center justify-between py-2 border-b">
                                        <span className="text-sm font-medium text-muted-foreground">System Version</span>
                                        <span className="text-sm font-bold">v2.5.1</span>
                                    </div>
                                    <div className="flex items-center justify-between py-2 border-b">
                                        <span className="text-sm font-medium text-muted-foreground">Database Version</span>
                                        <span className="text-sm font-bold">PostgreSQL 14.2</span>
                                    </div>
                                    <div className="flex items-center justify-between py-2 border-b">
                                        <span className="text-sm font-medium text-muted-foreground">Server Status</span>
                                        <Badge variant="secondary" className="bg-green-100 text-green-700 hover:bg-green-100 dark:bg-green-900/30 dark:text-green-400">Online</Badge>
                                    </div>
                                    <div className="flex items-center justify-between py-2 border-b">
                                        <span className="text-sm font-medium text-muted-foreground">Last Update</span>
                                        <span className="text-sm font-bold">January 10, 2025</span>
                                    </div>
                                    <div className="flex items-center justify-between py-2 border-b">
                                        <span className="text-sm font-medium text-muted-foreground">Storage Used</span>
                                        <span className="text-sm font-bold">2.4 GB / 10 GB</span>
                                    </div>
                                    <div className="flex items-center justify-between py-2">
                                        <span className="text-sm font-medium text-muted-foreground">Active Users</span>
                                        <span className="text-sm font-bold">24 / 24</span>
                                    </div>
                                    <Button variant="outline" className="w-full">
                                        <RefreshCw className="mr-2 h-4 w-4" />
                                        Check for Updates
                                    </Button>
                                </CardContent>
                            </Card>
                        </section>
                    </div>
                </div>
            </div>
        </AppLayout>
    );
}
